trailingComma = "es5"
useTabs = false
arrowParens = "avoid"
tabWidth = 4
semi = false
singleQuote = true
printWidth = 120
importOrder = ["^@/", "^[^@]", "^[./]"]
plugins = ["@trivago/prettier-plugin-sort-imports"]